In [1]:
import pandas as pd
import json
pd.set_option('display.max_columns', None)

## Exercice 1.1: Accord sur le signal "creative"
### 10.	Calculez le taux d’accord brut sur le label creative pour les paires où au moins deux utilisateurs ont réagi au même message.

In [2]:
from pathlib import Path
import pandas as pd

# This gets the directory where your notebook/script is located
base_dir = Path.cwd() 

# Build the path safely
file_path = base_dir.parent / "data" / "comparia-reactions" / "reactions.jsonl"

# Read the file
df_comparia_reactions = pd.read_json(file_path, lines=True)

In [3]:


df_comparia_reactions.head()

,id,timestamp,model_a_name,model_b_name,refers_to_model,msg_index,opening_msg,conversation_a,conversation_b,model_pos,conv_turns,conversation_pair_id,conv_a_id,conv_b_id,refers_to_conv_id,session_hash,visitor_id,response_content,question_content,liked,disliked,comment,useful,creative,complete,clear_formatting,incorrect,superficial,instructions_not_followed,model_pair_name,msg_rank,question_id,system_prompt
0,202099,2025-04-23 19:32:46.687,gemma-3-12b,command-a,command-a,1,Quelle est la stratégie commerciale du champag...,"[{'role': 'user', 'content': 'Quelle est la st...","[{'role': 'user', 'content': 'Quelle est la st...",b,1,1a62544c50474085b25240991e9fc620-6e6ffca415f44...,1a62544c50474085b25240991e9fc620,6e6ffca415f44bb88b781ec37b843420,6e6ffca415f44bb88b781ec37b843420,yl3mcxcqmz,64cfc81ae363a8abc31eaeff5387439f,La stratégie commerciale de **Champagne Nicola...,Quelle est la stratégie commerciale du champag...,True,False,,0.0,0.0,True,0.0,0.0,0.0,0.0,"[command-a, gemma-3-12b]",0,1a62544c50474085b25240991e9fc620-6e6ffca415f44...,NaN
1,176467,2025-03-25 13:41:21.988,llama-3.1-8b,claude-3-5-sonnet-v2,llama-3.1-8b,1,Qui est président en France ?,"[{'role': 'user', 'content': 'Qui est présiden...","[{'role': 'user', 'content': 'Qui est présiden...",a,1,ba089364a6e64d14b80eae6f7dd1885f-cda152aa7fe04...,ba089364a6e64d14b80eae6f7dd1885f,cda152aa7fe049f9ae0e02379f01f342,ba089364a6e64d14b80eae6f7dd1885f,4x178smu9v,3d3720ea8c5ff9dfbdbc886bd7ee7d00,Le président de la République française est ac...,Qui est président en France ?,True,False,,0.0,0.0,True,0.0,0.0,0.0,0.0,"[claude-3-5-sonnet-v2, llama-3.1-8b]",0,ba089364a6e64d14b80eae6f7dd1885f-cda152aa7fe04...,NaN
2,231166,2025-06-03 15:38:11.580,gpt-4.1-nano,llama-4-scout,llama-4-scout,1,tests logiciel,"[{'role': 'user', 'content': 'tests logiciel'}...","[{'role': 'user', 'content': 'tests logiciel'}...",b,1,e46e59300e8545038bfc22dfffb0b746-b006443eb1564...,e46e59300e8545038bfc22dfffb0b746,b006443eb1564f49b98a41b62b1078b3,b006443eb1564f49b98a41b62b1078b3,mwupf5ht3kr,bb1f75dbd09bcd96a6a2a95790c32f5c,Les tests logiciels ! Voici une vue d'ensemble...,tests logiciel,True,False,,0.0,0.0,True,0.0,0.0,0.0,0.0,"[gpt-4.1-nano, llama-4-scout]",0,e46e59300e8545038bfc22dfffb0b746-b006443eb1564...,NaN
3,264589,2025-08-20 13:52:02.676,llama-3.1-405b,mistral-large-2411,llama-3.1-405b,13,Vols au meilleur prix au départ de Marseille p...,"[{'role': 'user', 'content': 'Vols au meilleur...","[{'role': 'user', 'content': 'Vols au meilleur...",a,9,1f181e340b664f88b1aacc6770d0eeff-3f295419957c4...,1f181e340b664f88b1aacc6770d0eeff,3f295419957c465cb4c8713c5b600351,1f181e340b664f88b1aacc6770d0eeff,3bwjdjdu4gu,1299d615674a3add049c9869cf9eac1b,Le musée Harry Potter est un lieu de visite tr...,Intégrer la visite du musée Harry Potter dans ...,True,False,,1.0,0.0,False,0.0,0.0,0.0,0.0,"[llama-3.1-405b, mistral-large-2411]",6,1f181e340b664f88b1aacc6770d0eeff-3f295419957c4...,NaN
4,203152,2025-04-25 20:40:31.489,o4-mini,claude-3-7-sonnet,o4-mini,1,Comporte toi comme un expert en rédaction de p...,"[{'role': 'user', 'content': 'Comporte toi com...","[{'role': 'user', 'content': 'Comporte toi com...",a,1,5a646fd23c7c480dbbb9dac5f50b8c6d-5d343345ef294...,5a646fd23c7c480dbbb9dac5f50b8c6d,5d343345ef29439f915cbf3b3e9f82a6,5a646fd23c7c480dbbb9dac5f50b8c6d,yjz4oi5uzk,36ffd7b8de35fe20f4850fa9f45d88e1,Bonjour à toutes et à tous. \n\nImaginez un vo...,Comporte toi comme un expert en rédaction de p...,False,True,,0.0,0.0,False,0.0,0.0,1.0,0.0,"[claude-3-7-sonnet, o4-mini]",0,5a646fd23c7c480dbbb9dac5f50b8c6d-5d343345ef294...,NaN

In [4]:
df_comparia_reactions.columns

Index(['id', 'timestamp', 'model_a_name', 'model_b_name', 'refers_to_model',
       'msg_index', 'opening_msg', 'conversation_a', 'conversation_b',
       'model_pos', 'conv_turns', 'conversation_pair_id', 'conv_a_id',
       'conv_b_id', 'refers_to_conv_id', 'session_hash', 'visitor_id',
       'response_content', 'question_content', 'liked', 'disliked', 'comment',
       'useful', 'creative', 'complete', 'clear_formatting', 'incorrect',
       'superficial', 'instructions_not_followed', 'model_pair_name',
       'msg_rank', 'question_id', 'system_prompt'],
      dtype='str')

In [5]:
df_comparia_reactions.isnull().sum()

id                               0
timestamp                        0
model_a_name                     0
model_b_name                     0
refers_to_model                  0
msg_index                        0
opening_msg                      0
conversation_a                   0
conversation_b                   0
model_pos                        0
conv_turns                       0
conversation_pair_id             0
conv_a_id                        0
conv_b_id                        0
refers_to_conv_id                0
session_hash                     0
visitor_id                       0
response_content                 0
question_content                 0
liked                            0
disliked                         0
comment                        877
useful                         516
creative                       516
complete                         0
clear_formatting               516
incorrect                      516
superficial                    516
instructions_not_followed      516
model_pair_name                  0
msg_rank                         0
question_id                      0
system_prompt                63867
dtype: int64

In [6]:
df_comparia_reactions.shape

(94294, 33)

In [14]:
#afficher les lignes avec la même valeur de msg_index et conversation_pair_id et les regrouper ensemble
df_mm_message=df_comparia_reactions[df_comparia_reactions.duplicated(subset=['msg_index', 'conversation_pair_id'], keep=False)]
df_mm_message.groupby(['msg_index', 'conversation_pair_id']).size()

msg_index  conversation_pair_id
1          00034204d6994d8e99070b75b4fb3f67-2e5d7407743f474780bfe30bbca46148    2
           00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341bfadbe9e0ba611e1ba    2
           00084ec9d4b54b20841ab7decd9240be-3db325799f76410399b26c0e556504ec    2
           000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734fd391b058735388d9f0    2
           000ed32e609345a6ba595acacc23678f-58424a6cb5e641b8a50a9037b864da74    2
                                                                               ..
101        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    2
105        9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a35b103790b1645c069    2
107        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    2
109        9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a35b103790b1645c069    2
127        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    2
Length: 32786, dtype: int64

In [8]:
df_mm_message.groupby(['msg_index','conversation_pair_id']).agg(list)

                                                                            id  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [315701, 315705]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [126597, 126592]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...    [82935, 82938]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [307064, 307066]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [195480, 195482]
...                                                                        ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [140804, 140891]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [116818, 116728]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [141158, 141249]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [117138, 117047]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [142214, 142316]

                                                                                                      timestamp  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [2025-11-04 22:21:19.249000, 2025-11-04 22:22:...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [2025-02-27 18:37:50.619000, 2025-02-27 18:37:...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [2025-02-17 07:50:20.639000, 2025-02-17 07:50:...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [2025-10-21 21:51:31.723000, 2025-10-21 21:51:...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [2025-04-12 17:29:16.012000, 2025-04-12 17:29:...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [2025-03-01 07:06:41.832000, 2025-03-01 07:06:...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [2025-02-25 10:54:36.915000, 2025-02-25 10:54:...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [2025-03-01 07:07:04.761000, 2025-03-01 07:07:...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [2025-02-25 11:14:39.507000, 2025-02-25 11:14:...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [2025-03-01 07:08:18.105000, 2025-03-01 07:08:...

                                                                                                model_a_name  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...                      [gemma-3-27b, gemma-3-27b]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...          [gpt-4o-2024-08-06, gpt-4o-2024-08-06]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...    [claude-3-5-sonnet-v2, claude-3-5-sonnet-v2]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...                        [gpt-5-nano, gpt-5-nano]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [mistral-small-3.1-24b, mistral-small-3.1-24b]
...                                                                                                      ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...            [deepseek-v3-chat, deepseek-v3-chat]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...        [mistral-large-2411, mistral-large-2411]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...            [deepseek-v3-chat, deepseek-v3-chat]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...        [mistral-large-2411, mistral-large-2411]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...            [deepseek-v3-chat, deepseek-v3-chat]

                                                                                                  model_b_name  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...                    [llama-4-scout, llama-4-scout]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...            [gpt-4o-2024-08-06, gpt-4o-2024-08-06]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...              [gemini-2.0-flash, gemini-2.0-flash]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...          [mistral-small-2506, mistral-small-2506]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...                                [o3-mini, o3-mini]
...                                                                                                        ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [c4ai-command-r-08-2024, c4ai-command-r-08-2024]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...                    [llama-3.3-70b, llama-3.3-70b]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [c4ai-command-r-08-2024, c4ai-command-r-08-2024]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...                    [llama-3.3-70b, llama-3.3-70b]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [c4ai-command-r-08-2024, c4ai-command-r-08-2024]

                                                                                         refers_to_model  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...                [gemma-3-27b, llama-4-scout]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...      [gpt-4o-2024-08-06, gpt-4o-2024-08-06]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...    [claude-3-5-sonnet-v2, gemini-2.0-flash]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...            [mistral-small-2506, gpt-5-nano]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...            [mistral-small-3.1-24b, o3-mini]
...                                                                                                  ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [deepseek-v3-chat, c4ai-command-r-08-2024]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...         [mistral-large-2411, llama-3.3-70b]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [deepseek-v3-chat, c4ai-command-r-08-2024]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...         [mistral-large-2411, llama-3.3-70b]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [deepseek-v3-chat, c4ai-command-r-08-2024]

                                                                                                    opening_msg  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [make me a sexy story about two you slave girl...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [Fait moi un résumé tres détaillé d’environ 70...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [Je dois organiser un interclubs de boxe franç...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [Découvrir une nouvelle recette de cuisine. , ...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [Comment développer une IA au service de grand...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [Pourriais-tu, s'il te plaît, transformer le t...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [sous windows, comment lancer sqlite3.exe en l...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [Pourriais-tu, s'il te plaît, transformer le t...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [sous windows, comment lancer sqlite3.exe en l...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [Pourriais-tu, s'il te plaît, transformer le t...

                                                                                                 conversation_a  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [[{'role': 'user', 'content': 'make me a sexy ...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [[{'role': 'user', 'content': 'Fait moi un rés...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [[{'role': 'user', 'content': 'Je dois organis...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [[{'role': 'user', 'content': 'Découvrir une n...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [[{'role': 'user', 'content': 'Comment dévelop...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [[{'role': 'user', 'content': 'Pourriais-tu, s...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [[{'role': 'user', 'content': 'sous windows, c...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [[{'role': 'user', 'content': 'Pourriais-tu, s...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [[{'role': 'user', 'content': 'sous windows, c...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [[{'role': 'user', 'content': 'Pourriais-tu, s...

                                                                                                 conversation_b  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [[{'role': 'user', 'content': 'make me a sexy ...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [[{'role': 'user', 'content': 'Fait moi un rés...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [[{'role': 'user', 'content': 'Je dois organis...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [[{'role': 'user', 'content': 'Découvrir une n...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [[{'role': 'user', 'content': 'Comment dévelop...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [[{'role': 'user', 'content': 'Pourriais-tu, s...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [[{'role': 'user', 'content': 'sous windows, c...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [[{'role': 'user', 'content': 'Pourriais-tu, s...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [[{'role': 'user', 'content': 'sous windows, c...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [[{'role': 'user', 'content': 'Pourriais-tu, s...

                                                             model_pos  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...    [a, b]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...    [b, a]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...    [a, b]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...    [b, a]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...    [a, b]
...                                                                ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...    [a, b]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...    [a, b]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...    [a, b]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...    [a, b]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...    [a, b]

                                                             conv_turns  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...     [1, 1]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...     [1, 1]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...     [1, 1]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...     [1, 1]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...     [1, 1]
...                                                                 ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...   [69, 69]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...   [64, 64]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...   [69, 69]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...   [64, 64]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...   [69, 69]

                                                                                                      conv_a_id  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [00034204d6994d8e99070b75b4fb3f67, 00034204d69...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [00072aba380842e1afea00f70b01d9e7, 00072aba380...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [00084ec9d4b54b20841ab7decd9240be, 00084ec9d4b...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [000c9b3eb2bd41479d606579dcffa137, 000c9b3eb2b...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [000ed32e609345a6ba595acacc23678f, 000ed32e609...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [b0e8e9e00bc7457c9076e467350695a9, b0e8e9e00bc...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [9d1d675269854f02a228920c94e3e6e9, 9d1d6752698...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [b0e8e9e00bc7457c9076e467350695a9, b0e8e9e00bc...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [9d1d675269854f02a228920c94e3e6e9, 9d1d6752698...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [b0e8e9e00bc7457c9076e467350695a9, b0e8e9e00bc...

                                                                                                      conv_b_id  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [2e5d7407743f474780bfe30bbca46148, 2e5d7407743...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [fc968fd0b7f341bfadbe9e0ba611e1ba, fc968fd0b7f...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [3db325799f76410399b26c0e556504ec, 3db325799f7...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [1a8f8af84d734fd391b058735388d9f0, 1a8f8af84d7...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [58424a6cb5e641b8a50a9037b864da74, 58424a6cb5e...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [8c5d40afb50645ab82312716ef48fbaa, 8c5d40afb50...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [68475d05a8e24a35b103790b1645c069, 68475d05a8e...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [8c5d40afb50645ab82312716ef48fbaa, 8c5d40afb50...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [68475d05a8e24a35b103790b1645c069, 68475d05a8e...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [8c5d40afb50645ab82312716ef48fbaa, 8c5d40afb50...

                                                                                              refers_to_conv_id  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [00034204d6994d8e99070b75b4fb3f67, 2e5d7407743...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [fc968fd0b7f341bfadbe9e0ba611e1ba, 00072aba380...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [00084ec9d4b54b20841ab7decd9240be, 3db325799f7...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [1a8f8af84d734fd391b058735388d9f0, 000c9b3eb2b...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [000ed32e609345a6ba595acacc23678f, 58424a6cb5e...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [b0e8e9e00bc7457c9076e467350695a9, 8c5d40afb50...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [9d1d675269854f02a228920c94e3e6e9, 68475d05a8e...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [b0e8e9e00bc7457c9076e467350695a9, 8c5d40afb50...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [9d1d675269854f02a228920c94e3e6e9, 68475d05a8e...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [b0e8e9e00bc7457c9076e467350695a9, 8c5d40afb50...

                                                                                session_hash  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...      [2n49u29fell, 2n49u29fell]
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...      [avh4h3l7y2d, avh4h3l7y2d]
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [00h1wsxwt9zt8, 00h1wsxwt9zt8]
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...      [a7iycvh39ef, a7iycvh39ef]
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...      [wd9glpi37mi, wd9glpi37mi]
...                                                                                      ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...      [ir1kemz7bxj, ir1kemz7bxj]
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...      [5nqg614bwh6, 5nqg614bwh6]
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...      [ir1kemz7bxj, ir1kemz7bxj]
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...      [5nqg614bwh6, 5nqg614bwh6]
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...      [ir1kemz7bxj, ir1kemz7bxj]

                                                                                                     visitor_id  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [fc56866e083476414e83d6f9e3c7f278, fc56866e083...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [b7ec497101ad66c784128493cf0efb23, b7ec497101a...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [8659aecd52d8c27ac9abdb6d4be8beb6, 8659aecd52d...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [6f380410ae527b48ab48deecf53cbaeb, 6f380410ae5...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [c992c924997be7cc2d2905c228924d92, c992c924997...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
107       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
109       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
127       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...

                                                                                               response_content  \
msg_index conversation_pair_id
1         00034204d6994d8e99070b75b4fb3f67-2e5d7407743f47...  [I am programmed to be a safe and helpful AI a...
          00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341...  [Je suis désolé, mais je ne peux pas fournir u...
          00084ec9d4b54b20841ab7decd9240be-3db325799f7641...  [Voici un exemple de programme Python qui peut...
          000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734f...  [Si vous souhaitez découvrir une nouvelle rece...
          000ed32e609345a6ba595acacc23678f-58424a6cb5e641...  [Développer une intelligence artificielle (IA)...
...                                                                                                         ...
101       b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645...  [La Commission peut demander au fournisseur du...
105       9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a...  [La commande `.stats` dans SQLite est utilisée...

On voit que l'on a plusieurs messages qui ont été réagi par plusieurs utilisateurs. Nous allons calculer le taux d'accord brut sur le label "creative" pour ces messages.

In [15]:
df_mm_message.groupby(['msg_index','conversation_pair_id']).agg(list)["creative"]

msg_index  conversation_pair_id
1          00034204d6994d8e99070b75b4fb3f67-2e5d7407743f474780bfe30bbca46148    [0.0, 1.0]
           00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341bfadbe9e0ba611e1ba    [0.0, 0.0]
           00084ec9d4b54b20841ab7decd9240be-3db325799f76410399b26c0e556504ec    [0.0, 0.0]
           000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734fd391b058735388d9f0    [0.0, 0.0]
           000ed32e609345a6ba595acacc23678f-58424a6cb5e641b8a50a9037b864da74    [0.0, 0.0]
                                                                                   ...
101        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    [0.0, 0.0]
105        9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a35b103790b1645c069    [0.0, 0.0]
107        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    [0.0, 0.0]
109        9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a35b103790b1645c069    [0.0, 0.0]
127        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    [0.0, 0.0]
Name: creative, Length: 32786, dtype: object

In [17]:
df_mm_message.groupby(['msg_index','conversation_pair_id']).agg(list)["creative"].shape

(32786,)

In [23]:
# On regroupe
grouped = df_mm_message.groupby(['msg_index', 'conversation_pair_id'])['creative']

# On filtre : on ne garde que les groupes où le nombre d'entrées (count) est > 2
groupes_plus_de_2 = grouped.agg(list)[grouped.count() > 2]

print(groupes_plus_de_2)

Series([], Name: creative, dtype: object)

In [16]:
#calcul du taux d'accord brut sur le label creative pour les paires où au moins deux utilisateurs ont réagi au même message
liste_taux_accord_brut=[]
for list_creative in df_mm_message.groupby(['msg_index','conversation_pair_id']).agg(list)["creative"]:
    taux_actuel=0
    for i in range(len(list_creative)-1):
        for j in range(i+1,len(list_creative)):
            if list_creative[i]==list_creative[j]:
                taux_actuel+=1
    taux_actuel=taux_actuel/(len(list_creative)*(len(list_creative)-1)/2)
    liste_taux_accord_brut.append(taux_actuel)
print(liste_taux_accord_brut)

[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

On a que des groupes de 2, donc le taux d'accord brut est soit 0 (si les deux utilisateurs n'ont pas réagi de la même manière) soit 1 (si les deux utilisateurs ont réagi de la même manière). Nous allons calculer la moyenne de ces taux d'accord brut pour avoir une idée de l'accord global sur le signal "creative".

In [24]:
len(liste_taux_accord_brut)

32786

In [26]:
moyenne_taux_accord_brut=sum(liste_taux_accord_brut)/len(liste_taux_accord_brut)
print(moyenne_taux_accord_brut)

0.900628316964558

On voit que le score est très élevé, ce qui signifie que les utilisateurs sont globalement d'accord sur le signal "creative". Je voudrais vérifier que les utilisateurs qui ont réagi au même message sont différents, sinon cela fausserait le taux d'accord brut. Je vais vérifier cela en affichant les utilisateurs qui ont réagi au même message.

In [ ]:
df_mm_message.groupby(['msg_index','conversation_pair_id']).agg(list)["visitor_id"]

msg_index  conversation_pair_id
1          00034204d6994d8e99070b75b4fb3f67-2e5d7407743f474780bfe30bbca46148    [fc56866e083476414e83d6f9e3c7f278, fc56866e083...
           00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341bfadbe9e0ba611e1ba    [b7ec497101ad66c784128493cf0efb23, b7ec497101a...
           00084ec9d4b54b20841ab7decd9240be-3db325799f76410399b26c0e556504ec    [8659aecd52d8c27ac9abdb6d4be8beb6, 8659aecd52d...
           000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734fd391b058735388d9f0    [6f380410ae527b48ab48deecf53cbaeb, 6f380410ae5...
           000ed32e609345a6ba595acacc23678f-58424a6cb5e641b8a50a9037b864da74    [c992c924997be7cc2d2905c228924d92, c992c924997...
                                                                                                      ...
101        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
105        9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a35b103790b1645c069    [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
107        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
109        9d1d675269854f02a228920c94e3e6e9-68475d05a8e24a35b103790b1645c069    [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
127        b0e8e9e00bc7457c9076e467350695a9-8c5d40afb50645ab82312716ef48fbaa    [1b9cbc3a522cab330c07845e2c73b2bb, 1b9cbc3a522...
Name: visitor_id, Length: 32786, dtype: object

Oula on voit que beaucoup d'utilisateurs sont identiques, faissons un cleaning pour n'avoir que des groupes d'utilisateurs différents.

In [29]:
grouped = df_mm_message.groupby(['msg_index', 'conversation_pair_id'])
df_unique = grouped.filter(lambda x: x['visitor_id'].nunique() == len(x))
df_unique.groupby(['msg_index', 'conversation_pair_id']).agg(list)

Empty DataFrame
Columns: [id, timestamp, model_a_name, model_b_name, refers_to_model, msg_index, opening_msg, conversation_a, conversation_b, model_pos, conv_turns, conversation_pair_id, conv_a_id, conv_b_id, refers_to_conv_id, session_hash, visitor_id, response_content, question_content, liked, disliked, comment, useful, creative, complete, clear_formatting, incorrect, superficial, instructions_not_followed, model_pair_name, msg_rank, question_id, system_prompt]
Index: []

On en a aucun donc effectivement soit c'est des gens qui se sont corrigé soit c'est des gens qui ont réagi deux fois au même message.

### 11.	Calculez le κ de Cohen pour les conversations avec réactions multiples. Interprétez le résultat au regard des qualificatifs useful et complete (comparez leurs κ respectifs).

In [30]:
# trouver les conversations avec des réactions multiples
df_mm_conversation=df_comparia_reactions[df_comparia_reactions.duplicated(subset=['conversation_pair_id'], keep=False)]
df_mm_conversation.head(10)

,id,timestamp,model_a_name,model_b_name,refers_to_model,msg_index,opening_msg,conversation_a,conversation_b,model_pos,conv_turns,conversation_pair_id,conv_a_id,conv_b_id,refers_to_conv_id,session_hash,visitor_id,response_content,question_content,liked,disliked,comment,useful,creative,complete,clear_formatting,incorrect,superficial,instructions_not_followed,model_pair_name,msg_rank,question_id,system_prompt
1,176467,2025-03-25 13:41:21.988,llama-3.1-8b,claude-3-5-sonnet-v2,llama-3.1-8b,1,Qui est président en France ?,"[{'role': 'user', 'content': 'Qui est présiden...","[{'role': 'user', 'content': 'Qui est présiden...",a,1,ba089364a6e64d14b80eae6f7dd1885f-cda152aa7fe04...,ba089364a6e64d14b80eae6f7dd1885f,cda152aa7fe049f9ae0e02379f01f342,ba089364a6e64d14b80eae6f7dd1885f,4x178smu9v,3d3720ea8c5ff9dfbdbc886bd7ee7d00,Le président de la République française est ac...,Qui est président en France ?,True,False,,0.0,0.0,True,0.0,0.0,0.0,0.0,"[claude-3-5-sonnet-v2, llama-3.1-8b]",0,ba089364a6e64d14b80eae6f7dd1885f-cda152aa7fe04...,NaN
3,264589,2025-08-20 13:52:02.676,llama-3.1-405b,mistral-large-2411,llama-3.1-405b,13,Vols au meilleur prix au départ de Marseille p...,"[{'role': 'user', 'content': 'Vols au meilleur...","[{'role': 'user', 'content': 'Vols au meilleur...",a,9,1f181e340b664f88b1aacc6770d0eeff-3f295419957c4...,1f181e340b664f88b1aacc6770d0eeff,3f295419957c465cb4c8713c5b600351,1f181e340b664f88b1aacc6770d0eeff,3bwjdjdu4gu,1299d615674a3add049c9869cf9eac1b,Le musée Harry Potter est un lieu de visite tr...,Intégrer la visite du musée Harry Potter dans ...,True,False,,1.0,0.0,False,0.0,0.0,0.0,0.0,"[llama-3.1-405b, mistral-large-2411]",6,1f181e340b664f88b1aacc6770d0eeff-3f295419957c4...,NaN
4,203152,2025-04-25 20:40:31.489,o4-mini,claude-3-7-sonnet,o4-mini,1,Comporte toi comme un expert en rédaction de p...,"[{'role': 'user', 'content': 'Comporte toi com...","[{'role': 'user', 'content': 'Comporte toi com...",a,1,5a646fd23c7c480dbbb9dac5f50b8c6d-5d343345ef294...,5a646fd23c7c480dbbb9dac5f50b8c6d,5d343345ef29439f915cbf3b3e9f82a6,5a646fd23c7c480dbbb9dac5f50b8c6d,yjz4oi5uzk,36ffd7b8de35fe20f4850fa9f45d88e1,Bonjour à toutes et à tous. \n\nImaginez un vo...,Comporte toi comme un expert en rédaction de p...,False,True,,0.0,0.0,False,0.0,0.0,1.0,0.0,"[claude-3-7-sonnet, o4-mini]",0,5a646fd23c7c480dbbb9dac5f50b8c6d-5d343345ef294...,NaN
5,176470,2025-03-25 13:41:25.961,llama-3.1-8b,claude-3-5-sonnet-v2,claude-3-5-sonnet-v2,1,Qui est président en France ?,"[{'role': 'user', 'content': 'Qui est présiden...","[{'role': 'user', 'content': 'Qui est présiden...",b,1,ba089364a6e64d14b80eae6f7dd1885f-cda152aa7fe04...,ba089364a6e64d14b80eae6f7dd1885f,cda152aa7fe049f9ae0e02379f01f342,cda152aa7fe049f9ae0e02379f01f342,4x178smu9v,3d3720ea8c5ff9dfbdbc886bd7ee7d00,Emmanuel Macron est l'actuel président de la R...,Qui est président en France ?,False,True,,0.0,0.0,False,0.0,0.0,1.0,0.0,"[claude-3-5-sonnet-v2, llama-3.1-8b]",0,ba089364a6e64d14b80eae6f7dd1885f-cda152aa7fe04...,NaN
7,203157,2025-04-25 20:40:36.567,o4-mini,claude-3-7-sonnet,claude-3-7-sonnet,1,Comporte toi comme un expert en rédaction de p...,"[{'role': 'user', 'content': 'Comporte toi com...","[{'role': 'user', 'content': 'Comporte toi com...",b,1,5a646fd23c7c480dbbb9dac5f50b8c6d-5d343345ef294...,5a646fd23c7c480dbbb9dac5f50b8c6d,5d343345ef29439f915cbf3b3e9f82a6,5d343345ef29439f915cbf3b3e9f82a6,yjz4oi5uzk,36ffd7b8de35fe20f4850fa9f45d88e1,# Pourquoi un CD rayé peut-il continuer à lire...,Comporte toi comme un expert en rédaction de p...,True,False,,1.0,0.0,True,0.0,0.0,0.0,0.0,"[claude-3-7-sonnet, o4-mini]",0,5a646fd23c7c480dbbb9dac5f50b8c6d-5d343345ef294...,NaN
8,202100,2025-04-23 19:32:47.189,o4-mini,grok-3-mini-beta,grok-3-mini-beta,1,Comment transférer une sauvegarde de Farming s...,"[{'role': 'user', 'content': 'Comment transfér...","[{'role': 'user', 'content': 'Comment transfér...",b,1,3c9deb10725b43a3914f67ff20006d52-1d14eaf5eb844...,3c9deb10725b43a3914f67ff20006d52,1d14eaf5eb84462c9f107a85e0bc5bc6,1d14eaf5eb84462c9f107a85e0bc5bc6,y8s7e7qyiv,2943e08ba62c172c692a4dec6adc0e8b,Je vais vous expliquer comment transférer les ...,Comment transférer une sauvegarde de Farming s...,True,False,,1.0,0.0,True,1.0,0.0,0.0,0.0,"[grok-3-mini-beta, o4-mini]",0,3c9deb10725b43a3914f67ff20006d52-1d14eaf5eb844...,NaN
11,259107,2025-07-28 09:42:27.908,deepseek-v3-0324,mistral-saba,mistral-saba,1,Peux-tu reformuler : 6 aumôniers sont agréés a...,"[{'role': 'user', 'content': 'Peux-tu reformul...","[{'role': 'user', 'content': 'Peux-tu reformul...",b,1,bfb69fcb71ec48e0922f50ba2f0f777b-614e38b375404...,bfb69fcb71ec48e0922f50ba2f0f777b,614e38b37540441689487b225a967186,614e38b37540441689487b225a967186,rwcbdsrktwk,8fbe93b5e834f548c55e5f1374f1c9a6,"Six aumôniers sont accrédités au sein du CD, c...",Peux-tu reformuler : 6 aumôniers sont agréés a...,True,False,,0.0,0.0,False,0.0,0.0,0.0,0.0,"[deepseek-v3-0324, mistral-saba]",0,bfb69fcb71ec48e0922f50ba2f0f777b-614e38b375404...,NaN
12,176474,2025-03-25 13:41:34.885,deepseek-r1-distill-llama-70b,o3-mini,o3-mini,5,synthétiser : \nDepuis la loi du 11 février 20...,"[{'role': 'user', 'content': 'synthétiser : D...","[{'role': 'user', 'content': 'synthétiser : D...",b,4,afb770b038154643b170ee2b29f3c50a-3efac378fe4a4...,afb770b038154643b170ee2b29f3c50a,3efac378fe4a4af291463af52cd60ddb,3efac378fe4a4af291463af52cd60ddb,lcisfnwmzd,ab9c5a65adaf60382388a0c89bb4265f,Voici une synthèse du texte :\n\nDepuis la réf...,Synthétiser : Depuis la réforme du 17 juin 200...,True,False,,1.0,0.0,False,0.0,0.0,0.0,0.0,"[deepseek-r1-distill-llama-70b, o3-mini]",2,afb770b038154643b170ee2b29f3c50a-3efac378fe4a4...,NaN
13,202104,2025-04-23 19:32:56.846,o4-mini,grok-3-mini-beta,o4-mini,1,Comment transférer une sauvegarde de Farming s...,"[{'role': 'user', 'content': 'Comment transfér...","[{'role': 'user', 'content': 'Comment transfér...",a,1,3c9deb10725b43a3914f67ff20006d52-1d14eaf5eb844...,3c9deb10725b43a3914f67ff20006d52,1d14eaf5eb84462c9f107a85e0bc5bc6,3c9deb10725b43a3914f67ff20006d52,y8s7e7qyiv,2943e08ba62c172c692a4dec6adc0e8b,Voici une méthode « maison » pour récupérer TO...,Comment transférer une sauvegarde de Farming s...,False,True,,0.0,0.0,False,0.0,0.0,1.0,0.0,"[grok-3-mini-beta, o4-mini]",0,3c9deb10725b43a3914f67ff20006d52-1d14eaf5eb844...,NaN
15,247250,2025-06-25 12:21:22.056,gemma-3-12b,gemma-3-27b,gemma-3-27b,3,"du 25 au 29 mai 2026, nous souhaitons partir a...","[{'role': 'user', 'content': 'du 25 au 29 mai ...","[{'role': 'user', 'content': 'du 25 au 29 mai ...",b,2,cb880e778f9f45f893ad0f93b00721e4-32ebe0c47cf04...,cb880e778f9f45f893ad0f93b00721e4,32ebe0c47cf0405b8b4a8ba4418bd099,32ebe0c47cf0405b8b4a8ba4418bd099,qctnk3lvnt,cf8b69d49be505b3c7b648af158411bf,Travailler avec un établissement scolaire à Br...,avec quel établissement scolaire pouvons nous ...,True,False,,0.0,0.0,False,0.0,0.0,0.0,0.0,"[gemma-3-12b, gemma-3-27b]",1,cb880e778f9f45f893ad0f93b00721e4-32ebe0c47cf04...,NaN

In [31]:
df_mm_conversation.groupby(['conversation_pair_id']).agg(list)

,id,timestamp,model_a_name,model_b_name,refers_to_model,msg_index,opening_msg,conversation_a,conversation_b,model_pos,conv_turns,conv_a_id,conv_b_id,refers_to_conv_id,session_hash,visitor_id,response_content,question_content,liked,disliked,comment,useful,creative,complete,clear_formatting,incorrect,superficial,instructions_not_followed,model_pair_name,msg_rank,question_id,system_prompt
conversation_pair_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
00034204d6994d8e99070b75b4fb3f67-2e5d7407743f474780bfe30bbca46148,"[315701, 315705]","[2025-11-04 22:21:19.249000, 2025-11-04 22:22:...","[gemma-3-27b, gemma-3-27b]","[llama-4-scout, llama-4-scout]","[gemma-3-27b, llama-4-scout]","[1, 1]",[make me a sexy story about two you slave girl...,"[[{'role': 'user', 'content': 'make me a sexy ...","[[{'role': 'user', 'content': 'make me a sexy ...","[a, b]","[1, 1]","[00034204d6994d8e99070b75b4fb3f67, 00034204d69...","[2e5d7407743f474780bfe30bbca46148, 2e5d7407743...","[00034204d6994d8e99070b75b4fb3f67, 2e5d7407743...","[2n49u29fell, 2n49u29fell]","[fc56866e083476414e83d6f9e3c7f278, fc56866e083...",[I am programmed to be a safe and helpful AI a...,[make me a sexy story about two you slave girl...,"[False, True]","[True, False]",[shitty refusal the other made a nice kid frie...,"[0.0, 1.0]","[0.0, 1.0]","[False, True]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[[gemma-3-27b, llama-4-scout], [gemma-3-27b, l...","[0, 0]",[00034204d6994d8e99070b75b4fb3f67-2e5d7407743f...,"[nan, nan]"
00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341bfadbe9e0ba611e1ba,"[126597, 126592]","[2025-02-27 18:37:50.619000, 2025-02-27 18:37:...","[gpt-4o-2024-08-06, gpt-4o-2024-08-06]","[gpt-4o-2024-08-06, gpt-4o-2024-08-06]","[gpt-4o-2024-08-06, gpt-4o-2024-08-06]","[1, 1]",[Fait moi un résumé tres détaillé d’environ 70...,"[[{'role': 'user', 'content': 'Fait moi un rés...","[[{'role': 'user', 'content': 'Fait moi un rés...","[b, a]","[1, 1]","[00072aba380842e1afea00f70b01d9e7, 00072aba380...","[fc968fd0b7f341bfadbe9e0ba611e1ba, fc968fd0b7f...","[fc968fd0b7f341bfadbe9e0ba611e1ba, 00072aba380...","[avh4h3l7y2d, avh4h3l7y2d]","[b7ec497101ad66c784128493cf0efb23, b7ec497101a...","[Je suis désolé, mais je ne peux pas fournir u...",[Fait moi un résumé tres détaillé d’environ 70...,"[True, False]","[False, True]","[, Trop petit ]","[0.0, 0.0]","[0.0, 0.0]","[True, False]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 1.0]","[0.0, 0.0]","[[gpt-4o-2024-08-06, gpt-4o-2024-08-06], [gpt-...","[0, 0]",[00072aba380842e1afea00f70b01d9e7-fc968fd0b7f3...,"[, ]"
00084ec9d4b54b20841ab7decd9240be-3db325799f76410399b26c0e556504ec,"[82935, 82938]","[2025-02-17 07:50:20.639000, 2025-02-17 07:50:...","[claude-3-5-sonnet-v2, claude-3-5-sonnet-v2]","[gemini-2.0-flash, gemini-2.0-flash]","[claude-3-5-sonnet-v2, gemini-2.0-flash]","[1, 1]",[Je dois organiser un interclubs de boxe franç...,"[[{'role': 'user', 'content': 'Je dois organis...","[[{'role': 'user', 'content': 'Je dois organis...","[a, b]","[1, 1]","[00084ec9d4b54b20841ab7decd9240be, 00084ec9d4b...","[3db325799f76410399b26c0e556504ec, 3db325799f7...","[00084ec9d4b54b20841ab7decd9240be, 3db325799f7...","[00h1wsxwt9zt8, 00h1wsxwt9zt8]","[8659aecd52d8c27ac9abdb6d4be8beb6, 8659aecd52d...",[Voici un exemple de programme Python qui peut...,[Je dois organiser un interclubs de boxe franç...,"[True, True]","[False, False]","[, ]","[0.0, 0.0]","[0.0, 0.0]","[False, False]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[[claude-3-5-sonnet-v2, gemini-2.0-flash-exp],...","[0, 0]",[00084ec9d4b54b20841ab7decd9240be-3db325799f76...,"[, ]"
000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734fd391b058735388d9f0,"[307064, 307066]","[2025-10-21 21:51:31.723000, 2025-10-21 21:51:...","[gpt-5-nano, gpt-5-nano]","[mistral-small-2506, mistral-small-2506]","[mistral-small-2506, gpt-5-nano]","[1, 1]","[Découvrir une nouvelle recette de cuisine. , ...","[[{'role': 'user', 'content': 'Découvrir une n...","[[{'role': 'user', 'content': 'Découvrir une n...","[b, a]","[1, 1]","[000c9b3eb2bd41479d606579dcffa137, 000c9b3eb2b...","[1a8f8af84d734fd391b058735388d9f0, 1a8f8af84d7...","[1a8f8af84d734fd391b058735388d9f0, 000c9b3eb2b...","[a7iycvh39ef, a7iycvh39ef]","[6f380410ae527b48ab48deecf53cbaeb, 6f380410ae5...",[Si vous souhaitez découvrir une nouvelle rece...,"[Découvrir une nouvelle recette de cuisine. , ...","[True, False]","[False, True]","[, ]","[0.0, 0.0]","[0.0, 0.0]","[True, False]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 1.0]","[0.0, 0.0]","[[gpt-5-nano, mistral-small-2506], [gpt-5-nano...","[0, 0]",[000c9b3eb2bd41479d606579dcffa137-1a8f8af84d73...,"[nan, nan]"
000ed32e609345a6ba595acacc23678f-58424a6cb5e641b8a50a9037b864da74,"[195480, 195482]","[2025-04-12 17:29:16.012000, 2025-04-12 17:29:...","[mistral-small-3.1-24b, mistral-small-3.1-24b]","[o3-mini, o3-mini]","[mistral-small-3.1-24b, o3-mini]","[1, 1]",[Comment développer une IA au service de grand...,"[[{'role': 'user', 'content': 'Comment dévelop...","[[{'role': 'user', 'content': 'Comment dévelop...","[a, b]","[1, 1]","[000ed32e609345a6ba595acacc23678f, 000ed32e609...","[58424a6cb5e641b8a50a9037b864da74, 58424a6cb5e...","[000ed32e609345a6ba595acacc23678f, 58424a6cb5e...","[wd9glpi37mi, wd9glpi37mi]","[c992c924997be7cc2d2905c228924d92, c992c924997...",[Développer une intelligence artificielle (IA)...,[Comment développer une IA au service de grand...,"[True, True]","[False, False]","[, ]","[1.0, 1.0]","[0.0, 0.0]","[False, False]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[[mistral-small-3.1-24b, o3-mini], [mistral-sm...","[0, 0]",[000ed32e609345a6ba595acacc23678f-58424a6cb5e6...,"[nan, nan]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ffec794610784656ab18c32496ea65a9-0cf3964d4cac4aad9343e1d3d20fac81,"[336609, 336612, 336621]","[2025-11-19 15:01:38.414000, 2025-11-19 15:02:...","[gpt-5, gpt-5, gpt-5]","[claude-4-5-sonnet, claude-4-5-sonnet, claude-...","[gpt-5, claude-4-5-sonnet, claude-4-5-sonnet]","[5, 5, 11]",[J'aimerais faire une application sans serveur...,"[[{'role': 'user', 'content': 'J'aimerais fair...","[[{'role': 'user', 'content': 'J'aimerais fair...","[a, b, b]","[6, 6, 6]","[ffec794610784656ab18c32496ea65a9, ffec7946107...","[0cf3964d4cac4aad9343e1d3d20fac81, 0cf3964d4ca...","[ffec794610784656ab18c32496ea65a9, 0cf3964d4ca...","[sdkp3tosxhs, sdkp3tosxhs, sdkp3tosxhs]","[dc757126dfd98e4c0856810459c01fda, dc757126dfd...",[Je comprends l’idée: une appli web “sans serv...,"[nul nul nul, la version de chatgpt m'a propos...","[False, True, True]","[True, False, False]","[, , ]","[0.0, 1.0, 1.0]","[0.0, 1.0, 0.0]","[False, True, True]","[0.0, 0.0, 0.0]","[1.0, 0.0, 0.0]","[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0]","[[claude-4-5-sonnet, gpt-5], [claude-4-5-sonne...","[2, 2, 5]",[ffec794610784656ab18c32496ea65a9-0cf3964d4cac...,"[nan, nan, nan]"
ffeca0f688474b618689d2d91b083dc2-aa3c34c380d6445da36bf9d1b227e92f,"[303529, 303530]","[2025-10-16 11:03:04.720000, 2025-10-16 11:03:...","[claude-4-5-sonnet, claude-4-5-sonnet]","[gpt-5, gpt-5]","[gpt-5, claude-4-5-sonnet]","[1, 1]",[Peux tu dans un tableau faire un comparatif e...,"[[{'role': 'user', 'content': 'Peux tu dans un...","[[{'role': 'user', 'content': 'Peux tu dans un...","[b, a]","[1, 1]","[ffeca0f688474b618689d2d91b083dc2, ffeca0f6884...","[aa3c34c380d6445da36bf9d1b227e92f, aa3c34c380d...","[aa3c34c380d6445da36bf9d1b227e92f, ffeca0f6884...","[pk5ebgf484, pk5ebgf484]","[fc56866e083476414e83d6f9e3c7f278, fc56866e083...","[Oui. Pour être précis, j’ai besoin de deux cl...",[Peux tu dans un tableau faire un comparatif e...,"[False, True]","[True, False]","[, ]","[0.0, 1.0]","[0.0, 0.0]","[False, False]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[1.0, 0.0]","[[claude-4-5-sonnet, gpt-5], [claude-4-5-sonne...","[0, 0]",[ffeca0f688474b618689d2d91b083dc2-aa3c34c380d6...,"[nan, nan]"
fff02905c6304559a0d9ce13e895d4d5-9616cee1579d408d89d96a8e2b559352,"[23704, 23703]","[2025-01-22 10:14:09.256000, 2025-01-22 10:14:...","[llama-3.1-405b, llama-3.1-405b]","[gemini-2.0-flash, gemini-2.0-flash]","[llama-3.1-405b, gemini-2.0-flash]","[1, 1]",[Tu es un océanographe sur le navire de recher...,"[[{'role': 'user', 'content': 'Tu es un océano...","[[{'role': 'user', 'content': 'Tu es un océano...","[a, b]","[1, 1]","[fff02905c6304559a0d9ce13e895d4d5, fff02905c63...","[9616cee1579d408d89d96a8e2b559352, 9616cee1579...","[fff02905c6304559a0d9ce13e895d4d5, 9616cee1579...","[0dkwvgcds5vs, 0dkwvgcds5vs]","[918c93e1763859fd9d423e30e8ca6c8d, 918c93e1763...",[Quel privilège de travailler aux côtés du lég...,[Tu es un océanographe sur le navire de recher...,"[True, True]","[False, False]","[, ]","[1.0, 0.0]","[0.0, 0.0]","[False, False]","[0.0, 1.0]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[[gemini-2.0-flash-exp, llama-3.1-405b], [gemi...","[0, 0]",[fff02905c6304559a0d9ce13e895d4d5-9616cee1579d...,"[, ]"
fff1a42fce0f4f2b8c53651cd4f74838-cf3498ab4388440d826ac1b6fe31967f,"[185165, 185133]","[2025-04-01 12:45:58.526000, 2025-04-01 12:45:...","[c4ai-command-r-08-2024, c4ai-command-r-08-2024]","[deepseek-r1, deepseek-r1]","[c4ai-command-r-08-2024, deepseek-r1]","[1, 1]","[comment s’exprime le sexe gonadique ?, commen...","[[{'role': 'user', 'content': 'comment s’expri...","[[{'role': 'user', 'content': 'comment s’expri...","[a, b]","[1, 1]","[fff1a42fce0f4f2b8c53651cd4f74838, fff1a42fce0...","[cf3498ab4388440d826ac1b6fe31967f, cf3498ab438...","[fff1a42fce0f4f2b8c53651cd4f74838, cf3498ab438...","[0gxtjqlj91oe, 0gxtjqlj91oe]","[d197ff145bda3f6176ca86229c2cc4ce, d197ff145bd...",[Le sexe gonadique s'exprime par la présence e...,"[comment s’exprime le sexe gonadique ?, commen...","[True, True]","[False, False]","[, ]","[0.0, 0.0]","[0.0, 0.0]","[False, False]","[0.0, 1.0]","[0.0, 0.0]","[0.0, 0.0]","[0.0, 0.0]","[[c4ai-command-r-08-2024, deepseek-r1], [c4ai-...","[0, 0]",[fff1a42fce0f4f2b8c53651cd4f74838-cf3498ab4388...,"[nan, nan]"
fff81b3fbb3d4e11a24a0420504f100b-36fe2326bb33459abd7c980409417975,"[327750, 327754, 327758, 327748]","[2025-11-13 09:51:48.095000, 2025-11-13 09:52:...","[llama-3.3-70b, llama-3.3-70b, llama-3.3-70b, ...","[gpt-4.1-mini, gpt-4.1-mini, gpt-4.1-mini, gpt...","[llama-3.3-70b, llama-3.3-70b, gpt-4.1-mini, g...","[3, 1, 1, 3]",[Donne moi les conséquences de la grande dépre...,"[[{'role': 'user', 'content': 'Donne moi les c...","[[{'role': 'user', 'content': 'Donne moi les c...","[a, a, b, b]","[2, 2, 2, 2]","[fff81b3fbb3d4e11a24a0420504f100b, fff81b3fbb3...","[36fe2326bb33459abd7c980409417975, 36fe2326bb3...","[fff81b3fbb3d4e11a24a0420504f100b, fff81b3fbb3...","[7mpo4wml0fp, 7mpo4wml0fp, 7mpo4wml0fp, 7mpo4w...","[83df0dd2a15d1fd2b066753f94012855, 83df0dd2a15...",[La question qui a intrigué les Américains et ...,"[Qui a tue jfk,, Donne moi les conséquences de...","[True, True, True, False]","[False, False, False, True]","[Plus complète mais encore imparfaite, , , ]","[0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0]","[False, False, False, False]","[0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 1.0]","[0.0, 0.0, 0.0, 0.0]","[[gpt-4.1-mini, llama-3.3-70b], [gpt-4.1-mini,...","[1, 0, 0, 1]",[fff81b3fbb3d4e11a24a0420504f100b-36fe2326bb33...,"[nan, nan, nan, nan]"

In [36]:
from sklearn.metrics import cohen_kappa_score
from itertools import combinations

def compute_kappa(df, label, id_col='conversation_pair_id'):
    """
    Calcule le κ de Cohen pour un signal donné.

    Pour chaque conversation avec plusieurs réactions, extrait toutes les
    paires d'annotateurs (via combinaisons) et calcule le kappa global.

    Paramètres
    ----------
    df    : DataFrame contenant les réactions multiples (déjà filtré)
    label : nom de la colonne du signal ('creative', 'useful', 'complete')
    id_col: colonne identifiant les conversations (default: 'conversation_pair_id')

    Retourne
    --------
    float : valeur du κ de Cohen
    """
    ratings_a, ratings_b = [], []

    for _, group in df.groupby(id_col):
        labels = group[label].dropna().tolist()
        for a, b in combinations(labels, 2):
            ratings_a.append(a)
            ratings_b.append(b)

    if len(ratings_a) < 2:
        return float('nan')

    return cohen_kappa_score(ratings_a, ratings_b)

# Calcul du kappa pour chaque signal
k_cohen_creative  = compute_kappa(df_mm_conversation, 'creative')
k_cohen_useful    = compute_kappa(df_mm_conversation, 'useful')
k_cohen_complete  = compute_kappa(df_mm_conversation, 'complete')

print(f"κ de Cohen — creative  : {k_cohen_creative:.4f}")
print(f"κ de Cohen — useful    : {k_cohen_useful:.4f}")
print(f"κ de Cohen — complete  : {k_cohen_complete:.4f}")

κ de Cohen — creative  : 0.3184
κ de Cohen — useful    : 0.3625
κ de Cohen — complete  : 0.2973

### Interprétation

| Signal | κ de Cohen | Qualificatif (Landis & Koch) | Interprétation |
|--------|-----------|------------------------------|----------------|
| **useful** | 0.36 | Accord passable (0.21–0.40) | L'utilité est un critère relativement objectif ("la réponse répond-elle à la question ?"), d'où un accord entre annotateurs |
| **complete** | 0.29 | Accord passable (0.21–0.40) | La complétude a le kappa de Cohen le plus bas mais présentant un accord passable tout de même |
| **creative** | 0.31| Accord passable (0.21–0.40) | Un κ représentant un accord moyen mais il ne faut pas oublier que plusieurs annotateurs ont voté sur la même conversation cassant l'accord |

In [ ]:
nb_visitor_id_grouped = df_mm_conversation.groupby(['conversation_pair_id'])['visitor_id'].nunique()
print(nb_visitor_id_grouped.value_counts())

visitor_id
1    29502
Name: count, dtype: int64

In [41]:
#calculer erreur standard du kappa de Cohen pour le label creative
import numpy as np
def cohen_kappa_std_error(kappa, n):
    """
    Calcule l'erreur standard du kappa de Cohen.
    kappa : valeur du kappa de Cohen
    n : nombre total d'annotations (paires d'annotateurs)
    Hypothese : distribution binaire equilibree (pe = 0.5)
    """
    if n == 0:
        return float('nan')
    p0 = (kappa + 1) / 2  # Proportion d'accord observe
    pe = 0.5               # Proportion d'accord attendu (hypothese equilibree)
    var_kappa = p0 * (1 - p0) / (n * (1 - pe) ** 2)  # Formule de Fleiss
    return np.sqrt(var_kappa)
n_annotations = len(nb_visitor_id_grouped)
std_error_kappa_creative = cohen_kappa_std_error(k_cohen_creative, n_annotations)
print(f"Erreur standard du kappa de Cohen (creative) : {std_error_kappa_creative:.4f}")

Erreur standard du kappa de Cohen (creative) : 0.0055

## 12.	Formulez deux hypothèses sur les raisons pour lesquelles le signal creative est probablement plus bruité que le signal useful.

In [ ]:
df_mm_conversation.groupby(['conversation_pair_id']).agg(list)["creative"]

conversation_pair_id
00034204d6994d8e99070b75b4fb3f67-2e5d7407743f474780bfe30bbca46148              [0.0, 1.0]
00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341bfadbe9e0ba611e1ba              [0.0, 0.0]
00084ec9d4b54b20841ab7decd9240be-3db325799f76410399b26c0e556504ec              [0.0, 0.0]
000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734fd391b058735388d9f0              [0.0, 0.0]
000ed32e609345a6ba595acacc23678f-58424a6cb5e641b8a50a9037b864da74              [0.0, 0.0]
                                                                             ...
ffec794610784656ab18c32496ea65a9-0cf3964d4cac4aad9343e1d3d20fac81         [0.0, 1.0, 0.0]
ffeca0f688474b618689d2d91b083dc2-aa3c34c380d6445da36bf9d1b227e92f              [0.0, 0.0]
fff02905c6304559a0d9ce13e895d4d5-9616cee1579d408d89d96a8e2b559352              [0.0, 0.0]
fff1a42fce0f4f2b8c53651cd4f74838-cf3498ab4388440d826ac1b6fe31967f              [0.0, 0.0]
fff81b3fbb3d4e11a24a0420504f100b-36fe2326bb33459abd7c980409417975    [0.0, 0.0, 0.0, 0.0]
Name: creative, Length: 29502, dtype: object

In [ ]:
df_mm_conversation.groupby(['conversation_pair_id']).agg(list)["useful"]

conversation_pair_id
00034204d6994d8e99070b75b4fb3f67-2e5d7407743f474780bfe30bbca46148              [0.0, 1.0]
00072aba380842e1afea00f70b01d9e7-fc968fd0b7f341bfadbe9e0ba611e1ba              [0.0, 0.0]
00084ec9d4b54b20841ab7decd9240be-3db325799f76410399b26c0e556504ec              [0.0, 0.0]
000c9b3eb2bd41479d606579dcffa137-1a8f8af84d734fd391b058735388d9f0              [0.0, 0.0]
000ed32e609345a6ba595acacc23678f-58424a6cb5e641b8a50a9037b864da74              [1.0, 1.0]
                                                                             ...
ffec794610784656ab18c32496ea65a9-0cf3964d4cac4aad9343e1d3d20fac81         [0.0, 1.0, 1.0]
ffeca0f688474b618689d2d91b083dc2-aa3c34c380d6445da36bf9d1b227e92f              [0.0, 1.0]
fff02905c6304559a0d9ce13e895d4d5-9616cee1579d408d89d96a8e2b559352              [1.0, 0.0]
fff1a42fce0f4f2b8c53651cd4f74838-cf3498ab4388440d826ac1b6fe31967f              [0.0, 0.0]
fff81b3fbb3d4e11a24a0420504f100b-36fe2326bb33459abd7c980409417975    [0.0, 0.0, 0.0, 0.0]
Name: useful, Length: 29502, dtype: object

### Réponse

**Hypothèse 1 — Subjectivité inhérente du concept de créativité.**  

La créativité est une notion intrinsèquement subjective. Contrairement à *useful* ("la réponse a-t-elle aidé l'utilisateur ?") qui peut se vérifier factuellement, juger si une réponse est "créative" dépend des attentes esthétiques, du parcours culturel et des goûts personnels de l'annotateur. Deux annotateurs peuvent donc être en total désaccord tout en étant chacun cohérent avec sa propre définition interne de la créativité.

**Hypothèse 2 : L'applicabilité variable selon le type de requête (Context Mismatch).**

Le critère useful est universel : quel que soit le prompt (générer du code, répondre à une question d'histoire, écrire un poème), on peut toujours évaluer si la réponse a été utile à l'utilisateur.

À l'inverse, le critère creative n'est pas pertinent pour toutes les requêtes. Si un utilisateur demande "Comment calculer la TVA ?" ou "Corrige ce code Python", la réponse attendue doit être factuelle, pas créative.